apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: twilio-binding
spec:
  type: bindings.twilio.sms
  version: v1
  metadata:
    - name: toNumber
      value: ""
    - name: accountSid
      value: "AC8b2449ffe5b38b9c5e5787933ce0d0f6"
    - name: authToken
      value: "974374517516d04458d035e7c2626873"
    - name: fromNumber
      value: "+12316679128"
