apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: cm9vdA== # base64-encoded value of "root"
  POSTGRES_PASSWORD: YWRtaW4= # base64-encoded value of "admin"
  POSTGRES_DB: YWNjb3VudFNlcnZpY2U= # base64-encoded value of "accountService"
