apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/accountService
  SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
  SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  SERVER_PORT: "8083"
  SPRING_APPLICATION_NAME: ACCOUNT-SERVICE
  DAPR_HTTP_PORT: "3501"
  DAPR_APP_ID: account-service
  DAPR_APP_PORT: "8083"
  DAPR_HTTP_SERVICE: customer-service
  CUSTOMER_DAPR_URL: http://localhost:3500/v1.0/invoke/customer-service/method/customers/