apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
data:
  MONGO_URI: "mongodb+srv://root:admin@cluster0.buv7v.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  PORT: "8000"
  MONGODB_MAX_POOL_SIZE: "100"
  MONGODB_MIN_POOL_SIZE: "10"
  MONGODB_TIMEOUT_MS: "5000"
  ENV: "development"
  LOG_LEVEL: "INFO"
  APP_NAME: "banking-transaction-service"
  APP_VERSION: "1.0.0"
  API_V1_STR: "/api/v1"
  DAPR_STATE_URL: http://localhost:3500/v1.0/state/statestore
  ACCOUNT_SERVICE_URL: http://localhost:3500/v1.0/invoke/account-service/method/account
  pubsub_URL_updateAccount: http://localhost:3500/v1.0/publish/pubsub/updateAccount
  pubsub_URL_notify: http://localhost:3500/v1.0/publish/pubsub/notify
