apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "account-service"
        dapr.io/app-port: "8083"
        dapr.io/http-port: "3501"
    spec:
      containers:
      - name: account-service
        image: ahmeddhibi/account_service:latest
        ports:
        - containerPort: 8083
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: account-service-config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_USER
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_PASSWORD
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            valueFrom:
              configMapKeyRef:
                name: account-service-config
                key: SPRING_JPA_HIBERNATE_DDL_AUTO
          - name: SPRING_JPA_SHOW_SQL
            valueFrom:
              configMapKeyRef:
                name: account-service-config
                key: SPRING_JPA_SHOW_SQL
          - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
            valueFrom:
              configMapKeyRef:
                name: account-service-config
                key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: account-service-config
                key: SERVER_PORT
          - name: SPRING_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: account-service-config
                key: SPRING_APPLICATION_NAME
          - name: DAPR_HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: account-service-config
                key: DAPR_HTTP_PORT
          - name: DAPR_APP_ID
            valueFrom:
              configMapKeyRef:
                name: account-service-config
                key: DAPR_APP_ID
          - name: DAPR_APP_PORT
            valueFrom:
              configMapKeyRef:
                name: account-service-config
                key: DAPR_APP_PORT
          - name: DAPR_HTTP_SERVICE
            valueFrom:
              configMapKeyRef:
                name: account-service-config
                key: DAPR_HTTP_SERVICE
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 15

---
# Account Service HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: account-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: account-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70