apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4= # base64-encoded value of "admin"
#  MYSQL_USER: cm9vdA== # base64-encoded value of "root"
#  MYSQL_PASSWORD: YWRtaW4= # base64-encoded value of "admin"