# Account service allowed components and scopes
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: account-service-config
spec:
  accessControl:
    defaultAction: deny
    trustDomain: "public"
    policies:
      - appId: account-service
        defaultAction: allow
        trustDomain: "public"
        operations:
          - name: statestore-postgres
            httpVerb: ["GET", "POST", "PUT", "DELETE"]
            action: allow
          - name: pubsub
            httpVerb: ["POST", "PUT"]
            action: allow

---
# Customer service allowed components and scopes
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: customer-service-config
spec:
  accessControl:
    defaultAction: deny
    trustDomain: "public"
    policies:
      - appId: customer-service
        defaultAction: allow
        trustDomain: "public"
        operations:
          - name: statestore-mysql
            httpVerb: ["GET", "POST", "PUT", "DELETE"]
            action: allow
          - name: pubsub
            httpVerb: ["POST", "PUT"]
            action: allow

---
# Transaction service allowed components and scopes
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: transaction-service-config
spec:
  accessControl:
    defaultAction: deny
    trustDomain: "public"
    policies:
      - appId: transaction-service
        defaultAction: allow
        trustDomain: "public"
        operations:
          - name: statestore-mongodb
            httpVerb: ["GET", "POST", "PUT", "DELETE"]
            action: allow
          - name: pubsub
            httpVerb: ["POST", "PUT"]
            action: allow
