apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin:9411/api/v2/spans"
  metric:
    enabled: true
  serviceInvocation:
    maxRetries: 3
    maxRetryBackoffMs: 3000
  features:
    - name: ServiceInvocation
      enabled: true
    - name: StateManagement
      enabled: true
    - name: PubSub
      enabled: true

