apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      #initContainers:
      #- name: wait-for-pvc
      #  image: busybox
      #  command: ['sh', '-c', 'until [ -e /var/lib/mysql/data ]; do echo waiting for pvc; sleep 2; done;']
      #  volumeMounts:
      #  - name: mysql-storage
      #    mountPath: /var/lib/mysql/data
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mysql-secrets
        - configMapRef:
            name: mysql-config
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql/data
          subPath: mysql
  volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-pvc