name: CI Pipeline for account_service

on:
  push:
    branches: 
      - branch2
    paths:
      - 'account_service/**'
  pull_request:
    branches:
      - branch2

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./account_service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Make mvnw executable
    - name: Make mvnw executable
      run: chmod +x ./mvnw
    # Set up SonarQube Scanner
    - name: Set up SonarQube
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        sonar-token: ${{ secrets.SONAR_PASSWORD }}
        sonar-host-url: ${{ secrets.SONAR_URL }}

    # Run SonarQube analysis
    - name: Run SonarQube analysis
      run: ./mvnw clean verify sonar:sonar -Dsonar.projectKey=account_service

    # Set up JDK 17
    

    # Build with Maven
    - name: Build with Maven
      run: ./mvnw package -DskipTests

    # List target directory contents
    - name: List target directory contents
      run: ls -al ./target/
          
    # Upload artifact to Nexus
    - name: Upload artifact to Nexus
      run: |
        curl -v -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} --upload-file ./target/*.jar ${{ secrets.NEXUS_URL }}/repository/maven-releases/com/your-org/account_service/1.0.0/account_service-1.0.0.jar

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/account_service:latest .

    # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/account_service:latest
