name: CI Pipeline for Python Project

on:
  push:
    branches:
      - branch2
    paths:
      - "transaction/**"
  pull_request:
    branches:
      - branch2

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./transaction/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure all commit history is fetched for better analysis

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     source venv/bin/activate
      #     pytest --junitxml=results.xml  # Generate a test results report
      #   env:
      #     PYTHONPATH: ${{ github.workspace }}/transaction

      # - name: Archive test results
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-results
      #     path: results.xml

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-service:latest .

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/python-service:latest

  deployments:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up AKS credentials
        run: |
          az aks get-credentials --resource-group application --name kube --overwrite-existing

      - name: Deploy Transaction Microservice
        run: |
          kubectl apply -f ./k8s/deployments/transaction.yml
          kubectl apply -f ./k8s/services/transaction.yml
          sleep 10  # Wait for the deployment to be ready

      - name: Check Deployment Status
        run: |
          kubectl rollout status deployment/transaction

      - name: Get Pods Status
        run: |
          kubectl get pods -o wide

      - name: Retrieve Logs
        run: |
          kubectl logs -l app=transaction
